# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Common/mfp_nexys4_ddr.xdc

# IP: C:/JHU_Classes/Spring2026_DDR2/mig_example/mig_example.srcs/sources_1/ip/pll/pll.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pll || ORIG_REF_NAME==pll} -quiet] -quiet
